# Generated by Django 5.1 on 2024-09-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('category', models.CharField(choices=[('personal', 'personal'), ('business', 'business')], default='personal', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in-progress', 'in-progress'), ('done', 'done')], default='pending', max_length=200)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
